TV Arena: Capstone Project
NayanKaran/TV_Arena pull request #36
Opened 2022-06-23 15:53 UTC by NayanKaran

Hi,

We implemented the capstone project, with the following project requirements.

https://github.com/NayanKaran/TV_Arena/projects/1

Here is the link to the video explain the project:

https://www.youtube.com/watch?v=Dg2UtUWVpZE

Thank you.

2022-06-23 17:11 UTC, Davidosky007 requested changes
Hi @NayanKaran @wale-prog 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
* Welldone with the video presentation so far but your video lacks a highlight of some interesting piece of code or something you built that you are very proud of.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 17:11 UTC, Davidosky007 commented on src/modules/createCardUI.js
> +  const image = data._embedded.show.image.original;
*Kindly use the arrow function instead of the function keyword in all your codebase as es6 is a part of the[ learning objectives ](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.md#:~:text=single%20page%20apps.-,Use%20ES6%20syntax.,-Use%20ES6%20modules)

2022-06-24 09:25 UTC, NayanKaran commented
Hi,

We have re-recorded the video, presenting some of the interesting parts of the project.

Here is the [link](https://www.youtube.com/watch?v=CphtpLif3YA) to the video.

2022-06-24 09:37 UTC, OLIPLICHE approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 10:01 UTC, merged